### ISSUE TITLE
[CF] crash report dir, permission error

### ISSUE THREAD

**Issue by N0rimaki** [SnickCH/InsurgencySandstormDedicatedServer#3]
Starting the container brings this Message in the container logs.. relevant in any way?

```LogUnixPlatformFile: Warning: create dir('/home/steam/steamcmd/sandstorm/Insurgency/Saved/Config/CrashReportClient/UE4CC-Linux-470495B34CB94AA0BB0F7D74C43B16F0/CrashReportClient.ini') failed: errno=13 (Permission denied)```

**Comment by SnickCH** [comment]
As far as I see it, this is a permission problem on the host / docker system. A general troubl
Therefore I would close this issue, unles there are some people reporting this problem linked to the container instead of the host / docker permissions

https://stackoverflow.com/questions/56784492/permissionerror-errno-13-permission-denied-manage-py
