### ISSUE TITLE
Is that any document for Synology NAS user?

### ISSUE THREAD

**Issue by niat** [SnickCH/InsurgencySandstormDedicatedServer#9]
I am using Synology DS920 NAS, and its app, "Container Manager" (which replace docker) to install your project "Insurgency Sandstorm – customisable dedicated server"

Everything just work fine. 

After install  it can work fine, map open in farmhouse, AI working fine. 

My problem is:

Is that any variables to input? 

For example, I running minecraft java server on the same machine, this is how they provide the variables for user to change and setup on Container Manager ==> [https://docker-minecraft-server.readthedocs.io/en/latest/variables/]

As Container Manager just run a full install with its own process, we don't really input anything. 

As a new user, it make installation is very easy but at same time, I don't know where and how to adjust the value for some variables in server.

Another question, the directory setup:
I would like to know how to setup Data direntory, as I need to create config folder and adjust game.ini, etc ....

For minecraft, it bind "./data" to a folder for us to adjust and backup server data.

So ,there are two main issues for me:

1. I cannot adjust map, mapcycle, and Admin or server data changing because I don't know how to bind the data to a folder. 
2.  I don't know where to input data such as Max Players, GSLT token, Gamestatstoken,ruleset for the server.

Hoping you can help, thank you.

**Comment by SnickCH** [comment]
Everything for the container is documented in the main documentation of this project. 
There is no specific documentation for different platforms. 

1) You find all the information you asked in the docker-compose file
https://github.com/SnickCH/InsurgencySandstormDedicatedServer/blob/master/docker-compose.yml

In the "volume" part, you have the "mountpoints" you asked for the container

2) On "command" you find all the parts you ask. Some things you can also change with the ".ini" files. If you need to see how it is done via command line, please check the start_survival.sh example. If the questions are specific for Sandstorm I kindly ask you to check the documentation form the game itself.

https://github.com/SnickCH/InsurgencySandstormDedicatedServer/blob/master/Examples/Survival_Mods/start_survival.sh

I don't have a Synology NAS, therefore I can't test anything.

Synology documentation:
https://kb.synology.com/en-af/DSM/help/ContainerManager/docker_container?version=7
- Here you see the information you ask. Please check the examples from us and adjust them to your setup
-- "Volume: Specify the mount path for this container."
--" Execution command: Set the commands you want to run in the container." ->
-- "Port: Add this container's local ports. To find out which ports are exposed ports, check the image's Dockerfile."

If you have questions about our examples (docker-compose or start.sh) please feel free to ask - I'll try my best to help you. 
Than you very much for your understanding.

**Comment by niat** [comment]
Thank you for fast reply.

As I am also new user for this, maybe it is a lot thing I don't really understand, might get it wrongly.

It is because Container Manager make thing very easy, all image can install just one click and few setup, but what the cost is the easy install process replace the yml install, so I have to adjust the value on the UI provide by Container Manager not by sending command.

For example, if we want to create/edit files, folder, we have to bind a directory for it, in minecraft, we set /data to bind all server files for a folder we created.

But it need the information to tell us, use "/data" to bind the directory, which is my 1.Question for.

And for similar reason, we also need the other specify value/parameter to keyin on Container Manager UI for the server running not on the running command, because it just a button to run the server right now. This is my 2.Questoin for.

The UI on Container Manager look like this,
https://i.imgur.com/rESpyRW.png

This is the record for me, trying for change minecraft server type from Vanilla to Paper.
User need to know use "TYPE" as first field, then use "PAPER" on the right side for its value.

For your project, I do the same setup and it working fine without any extra setting(because I can't find any) with default, got 3 enemy AI when I join game, then I face this issue, ask for help to you.

I don't know if that is any where for me to find all valuable to do the customize setup for game server.

PS: this is my 1 minute install minecraft server record, for you to refer:
https://youtu.be/CYs1-MeMfwY
（sorry I am using Chinese UI for taiwan friends, I put double languages CC subtitle）

**Comment by SnickCH** [comment]
Hi Niat

I understand your question(s) and in my opinion they were answered in the first post. I think the challenge is, that you just startet with the game and maybe also have limited container experience (nothing personal :). I always try to help, also beginners. I will try my best to help you as far as possible:

About the game: Please check the game documentation where you have to change what kind of settings to get the setup you like. I’m the one that is keeping the container project alive but I’m not the server administrator (therefore I can’t really help you with specific game settings). Pleas also take a look at our examples because many settings are set in the .ini files (search there for «player» «count» «max» etc.) or please take a look at the offical documentation. Some of the parameters you ask are given as a command (documented in the project).

About containers: The link to the Synology documentation shows you exactly the parameters you ask. In the video you linked you see the same parameters. 

In our examples start.sh and the docker-compose.yml file you get the information you asked that are game specific. 

Example – static data ->check the docker-compose.yml and under volumes you will find
/x/x/x:/y/y/y

-	X is the path on your host (NAS) and y in the container. You have to change all the x part to your setup. The y path must be used 1:1 without any changes. One Example:

volumes:
      - /path/to/config/data/Game.ini:/home/steam/steamcmd/sandstorm/Insurgency/Saved/Config/LinuxServer/Game.ini:ro

You now need to change this for your setup: 
- /Your/NAS/PATH/Game.ini:/home/steam/steamcmd/sandstorm/Insurgency/Saved/Config/LinuxServer/Game.ini:ro

Commands: Please check the parameter from my first answer “Execution command:” here goes any command you want to give the server to start.

  command:
      -Port=27103
      -QueryPort=27133
      -Mods
      -Rcon
      -Mutators="Medic,ImprovedAI,ScaleSurvival,Vampirism,sBomber,PrintCount,JoinLeaveMessage,MoreAmmo"
      -ModDownloadTravelTo="Gap?Scenario=Scenario_Gap_Survival?lighting=day"
      -GSLTToken=YOURGSLTTOKEN
      -GameStatsToken=YOURGAMESTATSTOKEN


Synology documentation:
https://kb.synology.com/en-af/DSM/help/ContainerManager/docker_container?version=7

Here you see the information you ask. Please check the examples from us and adjust them to your setup
-- "Volume: Specify the mount path for this container."

As described above: here you have to setup all the volumes and files (like .ini). Please check the docker-compose.yml to get the path from the game and adjust it to your NAS. Above you have one example.

--" Execution command: Set the commands you want to run in the container."

Check the docker-compose.yml under “command”. I expect that you have to adjust the format for the NAS. Unfortunately the documentation from Synology doesn’t say anything about the details. 

-- "Port: Add this container's local ports. To find out which ports are exposed ports, check the image's Dockerfile."

This is done in the video you linked. The port information is in the start.sh and the docker-compose.yml file 


I hope this helps. Unfortunately without a good documentation from Synology I can only tell you what but not how you need to do it on your NAS.

I highly recommend you take some docker tutorials about the following points, so you better understand what is going on and then you know what to do. You will find many of them that are helpful :)
-	Docker: how to mount single file into container https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume
-	Docker: how do ports work 
-	Docker: How to add a command to the container start

Another approach could be to use docker-compose on your NAS (be sure that you know what you do, it is on your own risk and we can't give you support if something brakes). Short google search shows that many did this before. 

I hope this helps. I know that as a beginner this project may look confusing. In my experience all this "container managers" for NAS are very bad, because they hide a lot from you, the documentation is not really good and some of the options / parameters are not even available. I had a server admin that wanted to use portainer and the QNAP station. With portainer we were able to do it, but not with the QNAP NAS container station. 

If you have a specific question about this container image or documentation I'm happy to help. I thank you for your understanding that I can't do more for Synology NAS than give you the link to the documentation and mark you the parameters that are relevant for you. Maybe you can ask in a Synology forum for some support from people that have experience with this container manager. 

EDIT: Don't copy (all of) our commands if you don't use our MOD examples. We use some mutators in our examples that only work if you use the mod configuration 1:1.

**Comment by SnickCH** [comment]
Idea: Feel free to copy some screenshots when you set this up with the Synology NAS container station. So I see what you have as an option. Maybe I can help you with this if I see what you are doing and can point you in the right direction. No guarantee that this works. This is for the container setup (not the game settings)

Do me a favour: Please set the language of the menu to English  (in your link and video some things are in Chinese).

**Comment by niat** [comment]
I make some screenshots for you in English to refer, as last time that is Chinese UI.

And also, small result of testing for me this weekend, I finally found the correct value for the directory.

This is the one page - General for the Contanier:

https://i.imgur.com/s3nIIe5.png

Please ignore the chat system on the top-right side, which I forgot to close.

I skipped 2 page, as it is not working when Server not running.

It just showing how much CPU,RAM,Bandwidth used by it.

This is 3 page, this should be a log file or system message feedback to user. It look like some warning for me, but it can play when join game by LAN ip.

https://i.imgur.com/au3kLV3.png

This is the 4th page-setting:

https://i.imgur.com/vNPbjGo.png

Here is the main issue for me to trying, I don't know what parameter for me to create according the YML file you show me as refer.

You can see I trying to put some value on it(GSTToken), but look like nothing work, it still running on default setting.

I didn't try to setting Port or Query Port, as I think it should be set up on "Port setting" on the second top of the page.

I understand that if I run by command it might work, but what I hope is telling other how to setup the server in more simpler way by using Container Manager, even someone like me without much IT knowledge or experience, also could do.

That's why I trying to use more simple way to setup the server and try to make it simple enough for other to use it too.

I try the minecraft and it is quite simple as the value is that for user to search and use, but for Sandstorm I couldn't find any, it is impossible for me to guess what value or parameter to use or create.

I hope English version screenshot would help for our discussion, and thank you for spend time for this.

PS: I put the my Minecraft setting page on Container Manager here for you to refer 
https://i.imgur.com/aOQvwy0.png

**Comment by SnickCH** [comment]
I understand that you want «your» tool that you already used and everything as simple as possible. I want to point some things out

1. Everything from our project is documented. Even more: We also provided some examples for a fully fictional game server (it can be that some parameters changed, but this won't be a problem if it is only to get started)
2. All that is specific to the game is spart of the game documentation, not from our project. We are not the game developers.
3. We provided a docker-compose example and a start.sh example that you can use 1:1 as long as you install docker or docker-compose. Even with all .ini files that the game server runs. For beginners docker-compose is the way to go.
4. Unfortunately there is a minimum learning curve you must achieve if you want to adapt this to a specific container tool. Without any container knowhow this is not the best project to adapt it to another “management tool”
5. The question asked are mixed between: Were is it in the tool (answered with the link to the documentation to Synology NAS, here I try to help you) and were do I do what with the game (examples from us, here I kindly ask you to inform you about the game settings ore use our examples 1:1). 
6. I don't know how the container manager fro Synology makes sure you get new images and recreates the container. Just to be aware, that you get the new images all few days (or at least one time a week).

> “And also, small result of testing for me this weekend, I finally found the correct value for the directory. »

If you check the docker-compose.yml you see the «volume» section. This is exactly what you are asking. This ist he path from our local host to the container. The path in the container is there where the .ini files are located. You can look at the .ini files in our examples or even take them 1:1 if you like. The local path needs to be adapted. 

From your screen shot I see that you are missing the volumes and files. Don’t type “blindly” just any folders. This wont work – and you just typed the wrong folder. This won’t work on a long run and makes it even worse.
https://i.imgur.com/s3nIIe5.png
https://imgur.com/vNPbjGo


So please: Check my first reply with the link to the Synology NAS documentation. Then
1)	Create a folder on your nas and name it “sandstorm” (or similar). Then copy the ini files in this folder.
2)	Create a subfolder called “Mods”
3)	Make sure you use now your local path /your/nas/Sandstorm/Game.ini as the local path and don’t change the path inside the container. Just replace “/path/to/config/data/” with /your/nas/Sanstorm/ ->/your/nas/Sanstorm is just an example, you have to check your local path

Example (first line of the volumes would look like this) /your/nas/Sanstorm/Game.ini:/home/steam/steamcmd/sandstorm/Insurgency/Saved/Config/LinuxServer/Game.ini:ro
->only change the first part before the ":"

volumes: (better copy this directly from the docker-compose.yml)
      - /path/to/config/data/Game.ini:/home/steam/steamcmd/sandstorm/Insurgency/Saved/Config/LinuxServer/Game.ini:ro
      - /path/to/config/data/GameUserSettings.ini:/home/steam/steamcmd/sandstorm/Insurgency/Saved/Config/LinuxServer/GameUserSettings.ini:ro
      - /path/to/config/data/Admins.txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server/Admins.txt:ro
      - /path/to/config/data/Mods.txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server/Mods.txt:ro
      - /path/to/config/data/MapCycle.txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server/MapCycle.txt:ro
      - /path/to/mod/data/Mods/:/home/steam/steamcmd/sandstorm/Insurgency/Mods

The command part is exactly where you define GLS etc. (again: please take a look at the docker-compose.yml under command section). Environment variable is not the same as command. This won’t work. Here is the part where you unfortunately need some minimum container knowhow if you want to adapt it to another management tool. Please check in the link for the Synology documentation where you find in your setting the “command” section. 1:1 from my first post:

Synology documentation:
https://kb.synology.com/en-af/DSM/help/ContainerManager/docker_container?version=7
•	Here you see the information you ask. Please check the examples from us and adjust them to your setup
-- "Volume: Specify the mount path for this container."
--" Execution command: Set the commands you want to run in the container." -> here goes everything from the "command" part of the docker-compose.yml
-- "Port: Add this container's local ports. To find out which ports are exposed ports, check the image's Dockerfile."

I can only say again: My experience with this kind of NAS container manager is not really great. They often lack of features, don't have good documentation or make the management hard (like: auto update when new images are there). If you want to start with containers, I would take a look at docker-compose. For most of the end-user project you will find docker-compose examples. This makes your life much easier.

I'm happy to help, but I also ask you kindly to check the docker-compose.yml file and google the parts like "volumes" and "command" to better understand what is happening. This knowledge is important that you know what is going on and that you can adapt it for the Synology NAS.

**Comment by SnickCH** [comment]
Hint: your nas would even accept docker-compose.yml files according to this guide

https://www.wundertech.net/container-manager-on-a-synology-nas/

If this is the case: you only need to adapt the volume part

**Comment by niat** [comment]
Thank you for providing so many helps.

I understand it should be more complete for using YML to install the server, I think I will try to restart a new installation for server from YML, hoping this time get it work.

In meantime, it also mean this cannot run as easy as Minecraft server for who not so familiar to command type system.

The game environment in my mind, just trying to setup a PVE server having same setting as official public server, with maps day time only (I dislike night map), I got GST Token and Game stat Token, didn't planning for mods (At least not for learning stage right now).

So, I will try to make a try again by YML installation. 

Thank you once again.

**Comment by niat** [comment]
I try to use the YML example but it stuck at 1 step.

I cannot press "Next", because some error, look like sandstorm is not allowed to use?

I don't know why, any clue?

![YML issue](https://github.com/SnickCH/InsurgencySandstormDedicatedServer/assets/1298906/12653fe7-c3bb-44d0-b07c-01ff7a2d55e1)

I think the stat bar show me reason for the issue, but I don't now where should I adjust.

**Comment by SnickCH** [comment]
You are welcome. Sorry for the late reply. 

Can you please try the following

1. Rename the project "sandstorm" (so it has the same name as the service)
2. Can you make sure that in front of "sandstorm" is no "space"?
3. Can you make sure that everything above sandstorm is deleted (the two lines: one with the comment and one that is empty)? 

I validated the docker-compose.yml (it is valid). Please make sure when it is copy/paste into wizard (from your NAS) that the formatting is 1:1 as in the original file (insertion / spaces).

**Comment by SnickCH** [comment]
if this doesn't work, please add the following one line before sandstorm

`version: '3.5'`

Example:

```
version: '3.5'
sandstorm:
    image: snickch/insurgencysandstormdedicatedserver:latest
    container_name: sandstorm
    restart: always
```

etc.

If it complains about the version, just add 3.0 or 2.0 and see if it works.

**Comment by niat** [comment]
![same issue 20240202074844](https://github.com/SnickCH/InsurgencySandstormDedicatedServer/assets/1298906/8afc7435-d2af-424c-800b-f8509fadc24c)

I copied from this page.
https://github.com/SnickCH/InsurgencySandstormDedicatedServer/blob/master/docker-compose.yml

For testing I didn't change anything at first.

Now I try your suggestion 1,2,3.

Even version: '3.5' / version 3.0 / version 2.0, put on the line 1(delete all above text), nothings work.

I believe people normally got busy on weekdays, me also need for some free time to test this.

Thank you for helping.

**Comment by SnickCH** [comment]
Thank you for your feedback. On your printscreen I see that the two lines above the versioning are not deleted (but I expect from your text, that you did that).

"For testing I didn't change anything at first.": Please make sure that the path (volumes) are correct. 

Frankly: I don't know where the problem is. This is a working docker-compose.yml file. I don't know if the parsing of the file has another problem but just shows the "service name" (sandstorm)->kind of: bad error message.

What I would do 
- Make sure everything is correct. This includes the path ("volumes"). Just to make sure there is no other error that leads to this message. I had this issue with another container manager, when I helped a friend.
- Open a ticket at Synology and ask them for help. 

Unfortunately I have no other idea at the moment. 

If you give me your local path on the NAS where you want to store the data, I can help you with adjusting the correct path.
->I guess it is /docker/ins2 from your printscreen

**Comment by niat** [comment]
Yes, I open a new folder ( /docker/ins2) for this installation for trying install by YML file, because I don't want to use the old folder as it already got some files on it.

It show me error at the very beginning, I am not familiar enough for this kind of process, sorry cannot provide more information as I really don't know where or why cause this error.

I believe the 'sandstorm' is the error message as I click on the error message, it bring me to that line.

I try to follow your suggestion and do few time test, but not lucky, the outcome still same, I stuck at the first step.

I think your image of server is  working fine, it should be my problem because I just don't know the system.

When using the Container Manager simple way to install, although I cannot change any setting, but the server is running and can play with default setting.

Thank you for helping me, it is my problem for not enough knowledge or ability for this system.

**Comment by SnickCH** [comment]
I'm sorry that I can't help you more with the SynologyNAS Container Manager. 

One of the problem is the error code. Yes, it highlights "sandstorm" as the error - but it can just be, that it says "the service is not correct."  One of the reasons could be, because your paths are not correct in the configuration. 

Please make sure you set the correct path. 

/docker/ins2:/.....
/docker/ins2:/....
etc. 

And we remove the last part for watchtower. You have to create the folder "Mods" and to copy the .ini Files in the main folder (ins2).

Can you try this config (make sure the formatting is correct) - this is how your edited .yml file should look like (keep the original format, this is only to show you what you have to change)

sandstorm:
    image: snickch/insurgencysandstormdedicatedserver:latest
    container_name: sandstorm
    restart: always
    ports:
      - 27103:27103/tcp
      - 27103:27103/udp
      - 27133:27133/tcp
      - 27133:27133/udp
      - 29093:29093/tcp
      - 29093:29093/udp
    volumes:
      - /docker/ins2/Game.ini:/home/steam/steamcmd/sandstorm/Insurgency/Saved/Config/LinuxServer/Game.ini:ro
      - /docker/ins2/GameUserSettings.ini:/home/steam/steamcmd/sandstorm/Insurgency/Saved/Config/LinuxServer/GameUserSettings.ini:ro
      - /docker/ins2/Admins.txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server/Admins.txt:ro
      - /docker/ins2/Mods.txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server/Mods.txt:ro
      - /docker/ins2MapCycle.txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server/MapCycle.txt:ro
      - /docker/ins2Mods/:/home/steam/steamcmd/sandstorm/Insurgency/Mods
    entrypoint: ./InsurgencyServer-Linux-Shipping
    command:
      -Port=27103
      -QueryPort=27133
      -Mods
      -Rcon
      -Mutators="Medic,ImprovedAI,ScaleSurvival,Vampirism,sBomber,PrintCount,JoinLeaveMessage,MoreAmmo"
      -ModDownloadTravelTo="Gap?Scenario=Scenario_Gap_Survival?lighting=day"
      -GSLTToken=YOURGSLTTOKEN
      -GameStatsToken=YOURGAMESTATSTOKEN

**Comment by niat** [comment]
![20240210233817](https://github.com/SnickCH/InsurgencySandstormDedicatedServer/assets/1298906/d7435115-d7d1-409e-8c1a-5fafaec508d5)

Hello, my computer is out of order, it cause me late reply for this.

By using the code from last message, it bring more error (about 9-10 errors) , as I don't really understand the system, this is what I can feedback to you.

I try to screenshot all the error message, as below.

![error01](https://github.com/SnickCH/InsurgencySandstormDedicatedServer/assets/1298906/65ac6fb6-79b8-4fa4-8abd-1fa36deb78ca)

![error02](https://github.com/SnickCH/InsurgencySandstormDedicatedServer/assets/1298906/bbea7b77-cf52-409b-a4e5-7fe0ca50208a)

![error03](https://github.com/SnickCH/InsurgencySandstormDedicatedServer/assets/1298906/1c1002b0-56c9-4909-b808-fdb42921b256)

Thank you for helping.

**Comment by SnickCH** [comment]
You need to keep the formatting of the orignal docker-copose file, as described in my post above. 

The main problem is that you just copied it 1:1 without editing the format. Please take a look at our docker-compose example. and make sure you use the correct formatting (blank spaces before each section, it has a hierarchy that needs to be respected)

sandstom
-- next leve
...
-- -- next level 

etc. 

https://github.com/SnickCH/InsurgencySandstormDedicatedServer/blob/master/docker-compose.yml ->please open this file and check the formatting / hierarchy

**Comment by SnickCH** [comment]
I have not heard from you in 4 days. FYI: After 10 days without feedback I will close the request (thank you for your understanding).

**Comment by niat** [comment]
> I have not heard from you in 4 days. FYI: After 10 days without feedback I will close the request (thank you for your understanding).

It's ok, it is hard for you to helping me without the NAS and same platform, thank you very much.

I believe it need to adjust quite many things for fix in the contain manager from docker, it look different.

**Comment by SnickCH** [comment]
> > I have not heard from you in 4 days. FYI: After 10 days without feedback I will close the request (thank you for your understanding).
> 
> It's ok, it is hard for you to helping me without the NAS and same platform, thank you very much.
> 
> I believe it need to adjust quite many things for fix in the contain manager from docker, it look different.

You are welcome. If you have more questions about the project we are happy to help you. I will close the request. 
I wish you all the best and have fun with your game server :)
